version: '3.9'

services:
  web:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8001"
    volumes:
      - chroma-data:/chroma

volumes:
  chroma-data:
